/* Formatted on 7/13/2023 4:44:36 PM (QP5 v5.326) */

-- FINDING THE MISSING ORDER_NO

SELECT  G.ORDER_NO     MISSING_ORDER_NO
  FROM GR_ORDER G
 WHERE NOT EXISTS
           (SELECT B.ORDER_NO
              FROM GR_BULLETIN B, GR_BULLETINDTL BD
             WHERE     G.ORDER_NO = B.ORDER_NO
                   AND B.BULLETIN_NO = BD.BULLETIN_NO
                   AND B.ORDER_NO IS NOT NULL);


-- CREATING THE VIEW

CREATE OR REPLACE VIEW BULLETIN_SMV
AS
      SELECT B.ORDER_NO,
               SUM (NVL (BD.SAM_H, 0))
             + SUM (NVL (BD.SAM_I, 0))
             + SUM (NVL (BD.SAM_O, 0))
                 AS SMV
        FROM GR_BULLETIN B
             JOIN GR_BULLETINDTL BD ON B.BULLETIN_NO = BD.BULLETIN_NO
       WHERE B.ORDER_NO IS NOT NULL
    GROUP BY B.ORDER_NO;

SELECT * FROM BULLETIN_SMV;

-- SMV != SAM

SELECT BV.ORDER_NO, BV.SMV, GO.SAM
  FROM BULLETIN_SMV BV, GR_ORDER GO
 WHERE BV.ORDER_NO = GO.ORDER_NO AND BV.SMV <> GO.SAM;

-- SMV == SAM

SELECT BV.ORDER_NO, BV.SMV, GO.SAM
  FROM BULLETIN_SMV BV, GR_ORDER GO
 WHERE BV.ORDER_NO = GO.ORDER_NO AND BV.SMV = GO.SAM;